config/routes.rb
require "resque_web"
require 'resque-scheduler'
require 'resque/scheduler/server'

Rails.application.routes.draw do

  devise_for :users, path: "auth", path_names: {
     sign_in: 'login', 
     sign_out: 'logout', 
     password: 'secret', 
     confirmation: 'verification', 
     unlock: 'unblock', 
     registration: 'register', 
     sign_up: 'cmon_let_me_in' }
  
  resources :allis_buttons do
  end
  root to: 'allis_buttons#index', via: :get
  get 'auth/facebook', as: "auth_provider"
  get 'auth/facebook/callback', to: 'users#login'
  
  
  
    mount Resque::Server.new, at: '/resque_web', as: :resque_web

    resources :allis_button_styles

end

app/models/allis_button_style.rb
class AllisButtonStyle < ActiveRecord::Base
end

app/controllers/allis_button_styles_controller.rb
class AllisButtonStylesController < ApplicationController
  before_action :set_allis_button_style, only: [:show, :edit, :update, :destroy]

  # GET /allis_button_styles
  # GET /allis_button_styles.json
  def index
    @allis_button_styles = AllisButtonStyle.all
  end

  # GET /allis_button_styles/1
  # GET /allis_button_styles/1.json
  def show
  end

  # GET /allis_button_styles/new
  def new
    @allis_button_style = AllisButtonStyle.new
  end

  # GET /allis_button_styles/1/edit
  def edit
  end

  # POST /allis_button_styles
  # POST /allis_button_styles.json
  def create
    @allis_button_style = AllisButtonStyle.new(allis_button_style_params)

    respond_to do |format|
      if @allis_button_style.save
        format.html { redirect_to @allis_button_style, notice: 'Allis button style was successfully created.' }
        format.json { render :show, status: :created, location: @allis_button_style }
      else
        format.html { render :new }
        format.json { render json: @allis_button_style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allis_button_styles/1
  # PATCH/PUT /allis_button_styles/1.json
  def update
    respond_to do |format|
      if @allis_button_style.update(allis_button_style_params)
        format.html { redirect_to @allis_button_style, notice: 'Allis button style was successfully updated.' }
        format.json { render :show, status: :ok, location: @allis_button_style }
      else
        format.html { render :edit }
        format.json { render json: @allis_button_style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allis_button_styles/1
  # DELETE /allis_button_styles/1.json
  def destroy
    @allis_button_style.destroy
    respond_to do |format|
      format.html { redirect_to allis_button_styles_url, notice: 'Allis button style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allis_button_style
      @allis_button_style = AllisButtonStyle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allis_button_style_params
      params.require(:allis_button_style).permit(:name, :color)
    end
end

app/helpers/allis_button_styles_helper.rb
module AllisButtonStylesHelper
end

app/views/allis_button_styles/_form.html.erb
<%= form_for(@allis_button_style) do |f| %>
  <% if @allis_button_style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allis_button_style.errors.count, "error") %> prohibited this allis_button_style from being saved:</h2>

      <ul>
      <% @allis_button_style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/allis_button_styles/edit.html.erb
<h1>Editing Allis Button Style</h1>

<%= render 'form' %>

<%= link_to 'Show', @allis_button_style %> |
<%= link_to 'Back', allis_button_styles_path %>

app/views/allis_button_styles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Allis Button Styles</h1>

<table>
  <thead>
    <tr>
      <th>Color</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @allis_button_styles.each do |allis_button_style| %>
      <tr>
        <td><div class="color_preview" style="background-color:<%= allis_button_style.color %>"> </div></td>
        <td><%= allis_button_style.name %></td>
        <td><%= link_to 'Show', allis_button_style %></td>
        <td><%= link_to 'Edit', edit_allis_button_style_path(allis_button_style) %></td>
        <td><%= link_to 'Destroy', allis_button_style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Allis button style', new_allis_button_style_path %>

app/views/allis_button_styles/new.html.erb
<h1>New Allis Button Style</h1>

<%= render 'form' %>

<%= link_to 'Back', allis_button_styles_path %>

app/views/allis_button_styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @allis_button_style.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @allis_button_style.color %>
</p>

<%= link_to 'Edit', edit_allis_button_style_path(@allis_button_style) %> |
<%= link_to 'Back', allis_button_styles_path %>