config/routes.rb
require "resque_web"
require 'resque-scheduler'
require 'resque/scheduler/server'

Rails.application.routes.draw do

  devise_for :users, path: "auth", path_names: {
     sign_in: 'login', 
     sign_out: 'logout', 
     password: 'secret', 
     confirmation: 'verification', 
     unlock: 'unblock', 
     registration: 'register', 
     sign_up: 'cmon_let_me_in' }
  
  resources :allis_buttons do
  end
  root to: 'allis_buttons#index', via: :get
  get 'auth/facebook', as: "auth_provider"
  get 'auth/facebook/callback', to: 'users#login'
  
  
  
    mount Resque::Server.new, at: '/resque_web', as: :resque_web

    resources :allis_button_styles

end

app/models/allis_button.rb
class AllisButton < ActiveRecord::Base
  belongs_to :user
  before_save :default_values
   def default_values
     self.warns = 0
   end
end

app/controllers/allis_buttons_controller.rb
require 'date'
class AllisButtonsController < ApplicationController
  before_action :set_allis_button, only: [:show, :edit, :update, :destroy]

  # GET /allis_buttons
  # GET /allis_buttons.json
  def index
    @allis_buttons = AllisButton.all
  end

  # GET /allis_buttons/1
  # GET /allis_buttons/1.json
  def show
  end

  # GET /allis_buttons/new
  def new
    @allis_button = AllisButton.new
  end

  # GET /allis_buttons/1/edit
  def edit
  end
  def getTaskName(user_id, allis_button_id)
    'abc_'+ user_id.to_s + '_' + allis_button_id.to_s #change to {} format
  end
  # POST /allis_buttons
  # POST /allis_buttons.json
  def create
    @allis_button = AllisButton.new(allis_button_params)

    respond_to do |format|
      if @allis_button.save
        format.html { redirect_to @allis_button, notice: 'Allis button was successfully created.' }
        format.json { render :show, status: :created, location: @allis_button }
        #
        @user = User.find_by(id: @allis_button.user_id)
        name = self.getTaskName(@user.id, @allis_button.id)
        
        #config = {}
        #config[:queue] = 'AllisButtonCreated'
        #config[:class] = 'SendEmailJob'
        #config[:args] = @user.email
        #config[:every] = ['2m', {first_in: 10.seconds}]
        #config[:persist] = true
        #config[:verify_ssl] = false
    
        #Resque.set_schedule(name, config)
        #
        logger.info "I am trying to send an email trough a queue to:" + @user.email
        Resque.enqueue_in_with_queue('AllisButtonCreated',0.seconds, SendEmailJob, @user.email)
      else
        format.html { render :new }
        format.json { render json: @allis_button.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allis_buttons/1
  # PATCH/PUT /allis_buttons/1.json
  def update
    respond_to do |format|
      case params.require(:allis_button).permit(:update_action)[:update_action]
      when "check_only"
        @allis_button[:udate_date] = DateTime.now
        notice =  'Allis button was successfully checked.' + ' Time: ' + @allis_button[:udate_date].to_s
      else
        notice = 'Allis button was successfully updated.'
      end

      if @allis_button.update(allis_button_params)
        format.html { redirect_to @allis_button, notice: notice}
        format.json { render :show, status: :ok, location: @allis_button }
      else
        format.html { render :edit }
        format.json { render json: @allis_button.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allis_buttons/1
  # DELETE /allis_buttons/1.json
  def destroy
    @allis_button.destroy
    respond_to do |format|
      format.html { redirect_to allis_buttons_url, notice: 'Allis button was successfully destroyed.' }
      format.json { head :no_content }
    end
    name = self.getTaskName(@allis_button.user_id, @allis_button.id)
    Resque.remove_schedule(name)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allis_button
      @allis_button = AllisButton.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allis_button_params
      params.require(:allis_button).permit(:user_id, :word, :start_date, :udate_date, :interval, :subject_warning, :message_warning, :eml_warning, :style)
    end
end

app/helpers/allis_buttons_helper.rb
module AllisButtonsHelper
end

app/views/allis_buttons/_form.html.erb
<%= form_for(@allis_button) do |f| %>
  <% if @allis_button.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allis_button.errors.count, "error") %> prohibited this allis_button from being saved:</h2>

      <ul>
      <% @allis_button.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <% #f.text_field :user_id %>
	<%= f.collection_select :user_id, User.all, :id, :email, {:prompt => "Please select"} %>
  </div>
  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :style %><br>
	<%= f.collection_select :style, AllisButtonStyle.all, :name, :name,  {prompt:"choose a style"} %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.datetime_local_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :udate_date %><br>
    <%= f.datetime_local_field :udate_date %>
  </div>
  <div class="field">
    <%= f.label :interval %><br>
    <%= f.number_field :interval %>
  </div>
  <div class="field">
    <%= f.label :subject_warning %><br>
    <%= f.text_field :subject_warning %>
  </div>
  <div class="field">
    <%= f.label :message_warning %><br>
    <%= f.text_area :message_warning %>
  </div>
  <div class="field">
    <%= f.label :eml_warning %><br>
    <%= f.email_field :eml_warning %>
  </div>
  <!--div class="field">
    <%= f.label :warns %><br>
    <%= f.number_field :warns %>
  </div-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/allis_buttons/edit.html.erb
<h1>Editing Allis Button</h1>

<%= render 'form' %>

<%= link_to 'Show', @allis_button %> |
<%= link_to 'Back', allis_buttons_path %>

app/views/allis_buttons/index.html.erb
<%= render_navigation %>
<p id="notice"><%= notice %></p>

<h1>Listing Allis Buttons</h1>

<table>
  <thead>
    <tr>
      <th  width="150px">Button</th>
      <th>Start date</th>
      <th>Udate date</th>
      <th>Interval</th>
      <th>Subject warning</th>
      <th>Message warning</th>
      <th>Eml warning</th>
      <th>Warns</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @allis_buttons.each do |allis_button| %>
      <tr>
		<td>
			<%=form_for allis_button do |f|%>
				<%=f.hidden_field :update_action, value: 'check_only' %>
				<%=f.submit "All is " + allis_button.word, {:class => "allis-button " + allis_button.style}%>
			<% end%>
		</td>
        <td><%= allis_button.start_date %></td>
        <td><%= allis_button.udate_date %></td>
        <td><%= allis_button.interval %></td>
        <td><%= allis_button.subject_warning %></td>
        <td><%= allis_button.message_warning %></td>
        <td><%= allis_button.eml_warning %></td>
        <td><%= allis_button.warns %></td>
        <td><%= link_to 'Show', allis_button %></td>
        <td><%= link_to 'Edit', edit_allis_button_path(allis_button) %></td>
        <td><%= link_to 'Destroy', allis_button, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<%= link_to 'New Allis button', new_allis_button_path %>
<% end%>

app/views/allis_buttons/new.html.erb
<h1>New Allis Button</h1>

<%= render 'form' %>

<%= link_to 'Back', allis_buttons_path %>

app/views/allis_buttons/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>User:</strong>
  <%= @allis_button.user %>
</p>

<p>
  <strong>Word:</strong>
  <%= @allis_button.word %>
</p>

<p>
  <strong>Style:</strong>
  <%= @allis_button.style %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @allis_button.start_date %>
</p>

<p>
  <strong>Udate date:</strong>
  <%= @allis_button.udate_date %>
</p>

<p>
  <strong>Interval:</strong>
  <%= @allis_button.interval %>
</p>

<p>
  <strong>Subject warning:</strong>
  <%= @allis_button.subject_warning %>
</p>

<p>
  <strong>Message warning:</strong>
  <%= @allis_button.message_warning %>
</p>

<p>
  <strong>Eml warning:</strong>
  <%= @allis_button.eml_warning %>
</p>

<p>
  <strong>Warns:</strong>
  <%= @allis_button.warns %>
</p>

<%= link_to 'Edit', edit_allis_button_path(@allis_button) %> |
<%= link_to 'Back', allis_buttons_path %>